"""
test_writer.py

Converts parsed test-case specifications (from the LLM) into actual,
runnable pytest source files written to disk.

Design decision:
    Generated files are named `test_<module>_generated.py` and clearly
    marked with a header comment. They are never silently overwritten
    without being logged, and each generated test function embeds its
    `category` (happy_path / edge_case / error_case / boundary) as a
    pytest marker so CI can report pass/fail broken down by category —
    feeding directly into the historical trend analysis in storage/.
"""

from __future__ import annotations

import builtins
import logging
from pathlib import Path
from typing import Any

from ai_test_framework.scanner.repo_scanner import FunctionInfo

logger = logging.getLogger(__name__)

_HEADER = '''"""
AUTO-GENERATED by ai-test-framework. Do not edit by hand — regenerate instead.
Source function: {qualified_name} ({module_path})
"""
import pytest

'''


def _format_value(value: Any) -> str:
    """Render a Python literal for embedding in generated source."""
    if isinstance(value, str):
        return repr(value)
    return repr(value)


def _render_test_function(func: FunctionInfo, spec: dict[str, Any], import_path: str) -> str:
    name = spec.get("name", "test_generated_case")
    if not name.startswith("test_"):
        name = f"test_{name}"
    category = spec.get("category", "edge_case")
    description = spec.get("description", "")
    inputs: dict[str, Any] = spec.get("inputs", {})
    expected: dict[str, Any] = spec.get("expected", {})

    args_str = ", ".join(f"{k}={_format_value(v)}" for k, v in inputs.items())
    call_expr = f"{import_path}.{func.name}({args_str})"

    lines = [
        f'@pytest.mark.{category}',
        f"def {name}():",
        f'    """{description}"""',
    ]

    if "raises" in expected:
        exc_name = expected["raises"]
        lines.append(f"    with pytest.raises({exc_name}):")
        lines.append(f"        {call_expr}")
    else:
        expected_return = expected.get("returns")
        lines.append(f"    result = {call_expr}")
        if expected_return is not None:
            lines.append(f"    assert result == {_format_value(expected_return)}")
        else:
            lines.append("    assert result is not None  # TODO: refine assertion once behavior is confirmed")

    return "\n".join(lines) + "\n\n"


def _collect_exception_names(specs: list[dict[str, Any]]) -> list[str]:
    """Gather every distinct exception class name referenced via expected.raises."""
    names = {
        spec["expected"]["raises"]
        for spec in specs
        if "raises" in spec.get("expected", {})
    }
    return sorted(names)


def write_test_file(
    func: FunctionInfo,
    specs: list[dict[str, Any]],
    output_dir: Path,
    import_path: str,
) -> Path:
    """
    Write one generated test file for a single scanned function.

    `import_path` is the dotted module path the generated file should
    import from (e.g. "targets.sample_ecommerce_app.order_service").

    Any exception class referenced in a spec's `expected.raises` is
    imported directly from the same module as the function under test
    (custom exceptions and the function they guard conventionally live
    together) as well as from builtins, so `pytest.raises(SomeError)`
    resolves without a NameError at collection time — builtins like
    ValueError/KeyError are imported unconditionally since they always
    resolve and importing them from the target module would fail.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    module_name = import_path.split(".")[-1]
    file_path = output_dir / f"test_{module_name}_{func.name}_generated.py"

    header = _HEADER.format(qualified_name=func.qualified_name, module_path=func.module_path)

    import_line = f"import {import_path}\n"
    exception_names = _collect_exception_names(specs)
    custom_exceptions = [n for n in exception_names if not hasattr(builtins, n)]
    if custom_exceptions:
        import_line += f"from {import_path} import {', '.join(custom_exceptions)}\n"
    import_line += "\n\n"

    body = "\n".join(_render_test_function(func, spec, import_path) for spec in specs)

    file_path.write_text(header + import_line + body, encoding="utf-8")
    logger.info("Wrote %d generated test case(s) to %s", len(specs), file_path)
    return file_path
