"""
AUTO-GENERATED by ai-test-framework. Do not edit by hand — regenerate instead.
Source function: place_order (targets/sample_ecommerce_app/order_service.py)

This file is checked in as a REFERENCE EXAMPLE of real output quality from a
live OpenAI-backed generation run (see docs/usage.md for the before/after).
Running `ai-test-gen generate` will regenerate files like this into this
same directory.
"""
import pytest

from targets.sample_ecommerce_app.order_service import (
    InMemoryCatalog,
    InsufficientStockError,
    InvalidDiscountError,
    Product,
    place_order,
)


def _catalog_with_product(stock_qty: int = 10, unit_price_cents: int = 500) -> InMemoryCatalog:
    catalog = InMemoryCatalog()
    catalog.add_product(Product(sku="SKU-1", name="Widget", unit_price_cents=unit_price_cents, stock_qty=stock_qty))
    return catalog


@pytest.mark.happy_path
def test_place_order_happy_path():
    """Ordering a valid quantity within stock succeeds and decrements inventory."""
    catalog = _catalog_with_product(stock_qty=10)
    order = place_order(catalog, sku="SKU-1", quantity=2)
    assert order.total_cents == 1000
    assert catalog.get_product("SKU-1").stock_qty == 8


@pytest.mark.boundary
def test_place_order_exact_remaining_stock():
    """Ordering exactly the remaining stock quantity should succeed (boundary, not off-by-one)."""
    catalog = _catalog_with_product(stock_qty=5)
    order = place_order(catalog, sku="SKU-1", quantity=5)
    assert order.quantity == 5
    assert catalog.get_product("SKU-1").stock_qty == 0


@pytest.mark.error_case
def test_place_order_quantity_exceeds_stock_raises():
    """Ordering more than available stock raises InsufficientStockError."""
    catalog = _catalog_with_product(stock_qty=3)
    with pytest.raises(InsufficientStockError):
        place_order(catalog, sku="SKU-1", quantity=4)


@pytest.mark.edge_case
def test_place_order_zero_quantity_raises():
    """Zero is an invalid quantity, not a valid no-op order."""
    catalog = _catalog_with_product(stock_qty=10)
    with pytest.raises(InsufficientStockError):
        place_order(catalog, sku="SKU-1", quantity=0)


@pytest.mark.edge_case
def test_place_order_negative_quantity_raises():
    """Negative quantity must be rejected before any stock mutation occurs."""
    catalog = _catalog_with_product(stock_qty=10)
    with pytest.raises(InsufficientStockError):
        place_order(catalog, sku="SKU-1", quantity=-1)


@pytest.mark.error_case
def test_place_order_unknown_sku_raises_keyerror():
    """Referencing a SKU that doesn't exist in the catalog raises KeyError."""
    catalog = _catalog_with_product(stock_qty=10)
    with pytest.raises(KeyError):
        place_order(catalog, sku="DOES-NOT-EXIST", quantity=1)
